#include "generated.hpp"
#include "iec_test.hpp"
#include <cstring>

using namespace strucpp;

struct TestSetup_1 {
    FB_CYCLEMACHINEHOMING FB;
    ST_FBMACHINEHOMINGCYCLE_CFG CFG;
    ST_FBMACHINEHOMINGCYCLE_AXISHOMINGSTATUS STNONE;
    ST_FBMACHINEHOMINGCYCLE_AXISHOMINGSTATUS STHOMED;
    ST_FBMACHINEHOMINGCYCLE_AXISHOMINGSTATUS STERR;

    void setup() {
        CFG.CFGTOPHOMINGTARGET_M = 8.5;
        CFG.CFGOFFSETCLOSE_M = 0.2;
        CFG.CFGOFFSETOPEN_M = 1.0;
        CFG.CFGTIMEOUTCLIMB = 120000000000LL;
        CFG.CFGTIMEOUTHOMEAXES = 60000000000LL;
        STHOMED.HOMEDANDRELIABLE = true;
        STERR.HOMINGERROR = true;
    }

    void teardown() {
    }
};

// TEST 'TC-P09-H001 : HX0 n emet aucune sortie (hors maintenance, pas d auto-armement)'
bool test_1(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.TOPPOSITIONSENSOR = true;
        s.FB.WINCHESMECHANICALLYSTOPPED = false;
        s.FB.DEADMANARMED = true;
        s.FB.JOYSTICKPULL = true;
        s.FB.JOYSTICKDEFLECTED = true;
        s.FB.M1STATUS = s.STHOMED;
        s.FB.M2STATUS = s.STHOMED;
        s.FB.BUCKETOFFSETVALID = false;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(500000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX0_REPOS, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX0_REPOS", 40, "reste en HX0 hors maintenance")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMDWINCHM1.RUNREQUEST), "FB.CMDWINCHM1.RUNREQUEST", 41, "HX0 : aucun ordre treuil M1")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMDWINCHM2.RUNREQUEST), "FB.CMDWINCHM2.RUNREQUEST", 42, "HX0 : aucun ordre treuil M2")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMDBUCKETOPEN), "FB.CMDBUCKETOPEN", 43, "HX0 : aucun ordre benne ouverture")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMDBUCKETCLOSE), "FB.CMDBUCKETCLOSE", 44, "HX0 : aucun ordre benne fermeture")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.M1DEMAND.HOMEREQ), "FB.M1DEMAND.HOMEREQ", 45, "HX0 : aucun HomeReq")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.M3LOCKED), "FB.M3LOCKED", 46, "AC11 : HX0 -> translation M3 non verrouillee")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P09-H002 : auto-armement HX0 -> HX1 en maintenance (N1) non-homed'
bool test_2(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX0_REPOS, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX0_REPOS", 55, "SEMI_AUTO : reste HX0")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N1;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(400000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N1;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX1_CHOICE, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX1_CHOICE", 62, "MAINT_N1 non-homed : auto -> HX1")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.M3LOCKED), "FB.M3LOCKED", 63, "HX1 : M3 pas encore verrouillee (aucun mvt)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.MACHINEHOMINGACTIVE), "FB.MACHINEHOMINGACTIVE", 64, "HX1 : cycle pas encore actif")) return false;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSTEP, E_MACHINEHOMINGSTEP::OFFSET_UNKNOWN, "FB.MACHINEHOMINGSTEP", "E_MACHINEHOMINGSTEP.OFFSET_UNKNOWN", 65, "HX1 en N1 : consigne passer N2")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P09-H010 : validation 3 appuis HX1 -> HX2 en MAINT_N2 (pas sur capteur)'
bool test_3(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(400000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX1_CHOICE, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX1_CHOICE", 75, "auto -> HX1")) return false;
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(350000000);
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(350000000);
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(350000000);
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX2_CLIMB, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX2_CLIMB", 98, "3 appuis -> HX2")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.M3LOCKED), "FB.M3LOCKED", 99, "AC11 : M3 verrouillee des HX2 (cycle engage)")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P09-H012 : entree cycle sur front commande IHM StartRequest, en MAINT_N2'
bool test_4(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.STARTREQUEST = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(400000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.STARTREQUEST = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX0_REPOS, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX0_REPOS", 109, "SEMI_AUTO : StartRequest ignore")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.STARTREQUEST = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.STARTREQUEST = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX1_CHOICE, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX1_CHOICE", 115, "front StartRequest -> HX1")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P09-H011 : hors maintenance, ni auto ni motif ni StartRequest n arment'
bool test_5(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.STARTREQUEST = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(500000000);
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = false;
        s.FB.STARTREQUEST = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.STARTREQUEST = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX0_REPOS, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX0_REPOS", 127, "hors maintenance : reste HX0")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P09-H080 : NOT Enable -> sorties sures + MachineHomed FALSE + HX0'
bool test_6(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.TOPPOSITIONSENSOR = true;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.DEADMANARMED = true;
        s.FB.JOYSTICKPULL = true;
        s.FB.M1STATUS = s.STHOMED;
        s.FB.M2STATUS = s.STHOMED;
        s.FB.BUCKETOFFSETVALID = true;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.MACHINEHOMED), "FB.MACHINEHOMED", 136, "NOT Enable : MachineHomed FALSE")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMDWINCHM1.RUNREQUEST), "FB.CMDWINCHM1.RUNREQUEST", 137, "NOT Enable : treuil M1 sur")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMDWINCHM2.RUNREQUEST), "FB.CMDWINCHM2.RUNREQUEST", 138, "NOT Enable : treuil M2 sur")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.M3LOCKED), "FB.M3LOCKED", 139, "NOT Enable : verrou M3 relache")) return false;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX0_REPOS, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX0_REPOS", 140, "NOT Enable : HX0")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P09-H082 : perte de datum EN MOUVEMENT -> SafeStop latche jusqu a arret + Reset'
bool test_7(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STHOMED;
        s.FB.M2STATUS = s.STHOMED;
        s.FB.BUCKETOFFSETVALID = true;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.MACHINEHOMED), "FB.MACHINEHOMED", 150, "datum initial valide")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STHOMED;
        s.FB.BUCKETOFFSETVALID = true;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.MACHINEHOMINGLOSSSAFESTOP), "FB.MACHINEHOMINGLOSSSAFESTOP", 153, "SafeStop demande sur perte en mouvement")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.MACHINEHOMED), "FB.MACHINEHOMED", 154, "MachineHomed retombe")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STHOMED;
        s.FB.M2STATUS = s.STHOMED;
        s.FB.BUCKETOFFSETVALID = true;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.MACHINEHOMINGLOSSSAFESTOP), "FB.MACHINEHOMINGLOSSSAFESTOP", 157, "SafeStop retombe a l arret")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.MACHINEHOMED), "FB.MACHINEHOMED", 158, "pas de redemarrage auto : MachineHomed reste FALSE")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STHOMED;
        s.FB.M2STATUS = s.STHOMED;
        s.FB.BUCKETOFFSETVALID = true;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STHOMED;
        s.FB.M2STATUS = s.STHOMED;
        s.FB.BUCKETOFFSETVALID = true;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.MACHINEHOMED), "FB.MACHINEHOMED", 163, "Reset conscient : datum de nouveau valide")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P09-H090 : guide BOTH_NOT_HOMED, entree cycle, AC4, HomingError -> FAILED'
bool test_8(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::SEMI_AUTO;
        s.FB.TOPPOSITIONSENSOR = false;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSTEP, E_MACHINEHOMINGSTEP::BOTH_NOT_HOMED, "FB.MACHINEHOMINGSTEP", "E_MACHINEHOMINGSTEP.BOTH_NOT_HOMED", 173, "BOTH_NOT_HOMED hors cycle")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(400000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX1_CHOICE, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX1_CHOICE", 180, "auto -> HX1")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(350000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(350000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(350000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.WINCHESMECHANICALLYSTOPPED = true;
        s.FB.BTNVALIDATION = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX2_CLIMB, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX2_CLIMB", 203, "3 appuis -> HX2")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.M3LOCKED), "FB.M3LOCKED", 204, "AC11 : M3 verrouillee des HX2 (cycle engage)")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.TOPPOSITIONSENSOR = false;
        s.FB.WINCHESMECHANICALLYSTOPPED = false;
        s.FB.DEADMANARMED = true;
        s.FB.JOYSTICKPULL = true;
        s.FB.JOYSTICKDEFLECTED = true;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMDWINCHM1.RUNREQUEST), "FB.CMDWINCHM1.RUNREQUEST", 209, "AC4 : montee M1 sous permis")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMDWINCHM1.REQASCENT), "FB.CMDWINCHM1.REQASCENT", 210, "AC4 : sens montee M1")) return false;
        if (!ctx.assert_eq(s.FB.CMDWINCHM1.STEPTGT, 1, "FB.CMDWINCHM1.STEPTGT", "1", 211, "AC4 : palier 1")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.TOPPOSITIONSENSOR = false;
        s.FB.WINCHESMECHANICALLYSTOPPED = false;
        s.FB.DEADMANARMED = false;
        s.FB.JOYSTICKPULL = false;
        s.FB.JOYSTICKDEFLECTED = false;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMDWINCHM1.RUNREQUEST), "FB.CMDWINCHM1.RUNREQUEST", 216, "AC4 : coupure au relachement permis")) return false;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX2_CLIMB, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX2_CLIMB", 217, "AC4 : etape conservee")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.TOPPOSITIONSENSOR = false;
        s.FB.WINCHESMECHANICALLYSTOPPED = false;
        s.FB.DEADMANARMED = true;
        s.FB.JOYSTICKPULL = true;
        s.FB.JOYSTICKDEFLECTED = true;
        s.FB.M1STATUS = s.STERR;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HXF_FAILED, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HXF_FAILED", 222, "AC6 : HomingError -> HXF")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.FAULT.LATCHED), "FB.FAULT.LATCHED", 223, "defaut latche")) return false;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSTEP, E_MACHINEHOMINGSTEP::FAILED, "FB.MACHINEHOMINGSTEP", "E_MACHINEHOMINGSTEP.FAILED", 224, "AC12 : guide FAILED sur Fault.Latched")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HXF_FAILED, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HXF_FAILED", 227, "AC10 : pas de sortie auto")) return false;
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.MODE = E_MODE::MAINT_N2;
        s.FB.M1STATUS = s.STNONE;
        s.FB.M2STATUS = s.STNONE;
        s.FB.CFG = s.CFG;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.MACHINEHOMINGSEQSTEP, E_MACHINEHOMINGTXSTATE::HX0_REPOS, "FB.MACHINEHOMINGSEQSTEP", "E_MACHINEHOMINGTXSTATE.HX0_REPOS", 229, "AC10 : Reset -> HX0")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

int main(int argc, char* argv[]) {
    bool json_mode = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--json") == 0) { json_mode = true; break; }
    }

    strucpp::TestRunner runner("test_fb_cyclemachinehoming.st");
    runner.set_json_mode(json_mode);
    runner.add("TC-P09-H001 : HX0 n emet aucune sortie (hors maintenance, pas d auto-armement)", test_1);
    runner.add("TC-P09-H002 : auto-armement HX0 -> HX1 en maintenance (N1) non-homed", test_2);
    runner.add("TC-P09-H010 : validation 3 appuis HX1 -> HX2 en MAINT_N2 (pas sur capteur)", test_3);
    runner.add("TC-P09-H012 : entree cycle sur front commande IHM StartRequest, en MAINT_N2", test_4);
    runner.add("TC-P09-H011 : hors maintenance, ni auto ni motif ni StartRequest n arment", test_5);
    runner.add("TC-P09-H080 : NOT Enable -> sorties sures + MachineHomed FALSE + HX0", test_6);
    runner.add("TC-P09-H082 : perte de datum EN MOUVEMENT -> SafeStop latche jusqu a arret + Reset", test_7);
    runner.add("TC-P09-H090 : guide BOTH_NOT_HOMED, entree cycle, AC4, HomingError -> FAILED", test_8);
    return runner.run();
}
