#include "generated.hpp"
#include "iec_test.hpp"
#include <cstring>

using namespace strucpp;

struct TestSetup_1 {
    FB_WINCH_SYMMETRY FB;
    ST_FBWINCH_SYMMETRY_CFG CFG;
    ST_FBWINCH_SYMMETRY_DATA DAT;

    void setup() {
    }

    void teardown() {
    }
};

// TEST 'TC-P10-T181-18a Cycle symetrique -> SymmetryValid et SymmetryOk'
bool test_1(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.CFG.MINIMUMCOMMANDTIME_MS = 300;
        s.CFG.MINIMUMSPEED_MPS = 0.05;
        s.CFG.DELTASTARTDELAY_MS = 100;
        s.CFG.DELTABRAKERELEASETIME_MS = 100;
        s.CFG.DELTABRAKEAPPLYTIME_MS = 100;
        s.CFG.DELTASTOPDISTANCE_MM = 100;
        s.CFG.DELTASTOPTIME_MS = 200;
        s.FB.RESET = true;
        s.FB.M1COMMANDACTIVE = false;
        s.FB.M2COMMANDACTIVE = false;
        s.FB.M1DIRECTION = 0;
        s.FB.M2DIRECTION = 0;
        s.FB.M1BRAKECMD = false;
        s.FB.M2BRAKECMD = false;
        s.FB.M1BRAKEAPPLIED = true;
        s.FB.M2BRAKEAPPLIED = true;
        s.FB.M1POSITION_M = 0.0;
        s.FB.M2POSITION_M = 0.0;
        s.FB.M1SPEED_MPS = 0.0;
        s.FB.M2SPEED_MPS = 0.0;
        s.FB.SYNCDEVIATION_M = 0.0;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = true;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = true;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = false;
        s.FB.M1POSITION_M = 0.0;
        s.FB.M2POSITION_M = 0.0;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 1.0;
        s.FB.SYNCDEVIATION_M = 0.1;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(500000000);
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = true;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = true;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = false;
        s.FB.M1POSITION_M = 0.5;
        s.FB.M2POSITION_M = 0.5;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 1.0;
        s.FB.SYNCDEVIATION_M = 0.1;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(500000000);
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = true;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = true;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = false;
        s.FB.M1POSITION_M = 1.0;
        s.FB.M2POSITION_M = 1.0;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 1.0;
        s.FB.SYNCDEVIATION_M = 0.1;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(500000000);
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = true;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = true;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = false;
        s.FB.M1POSITION_M = 1.5;
        s.FB.M2POSITION_M = 1.5;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 1.0;
        s.FB.SYNCDEVIATION_M = 0.1;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(500000000);
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = false;
        s.FB.M2COMMANDACTIVE = false;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = false;
        s.FB.M2BRAKECMD = false;
        s.FB.M1BRAKEAPPLIED = true;
        s.FB.M2BRAKEAPPLIED = true;
        s.FB.M1POSITION_M = 2.0;
        s.FB.M2POSITION_M = 2.0;
        s.FB.M1SPEED_MPS = 0.0;
        s.FB.M2SPEED_MPS = 0.0;
        s.FB.SYNCDEVIATION_M = 0.0;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = false;
        s.FB.M2COMMANDACTIVE = false;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = false;
        s.FB.M2BRAKECMD = false;
        s.FB.M1BRAKEAPPLIED = true;
        s.FB.M2BRAKEAPPLIED = true;
        s.FB.M1POSITION_M = 2.0;
        s.FB.M2POSITION_M = 2.0;
        s.FB.M1SPEED_MPS = 0.0;
        s.FB.M2SPEED_MPS = 0.0;
        s.FB.SYNCDEVIATION_M = 0.0;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        if (!ctx.assert_true(static_cast<bool>(s.FB.SYMMETRYVALID), "FB.SYMMETRYVALID", 56, "Cycle complet qualifie puis arrete -> mesure valide")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.SYMMETRYOK), "FB.SYMMETRYOK", 57, "M1 et M2 identiques -> tous les ecarts sous les seuils")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-T181-18b Reset remet les mesures a zero'
bool test_2(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.CFG.MINIMUMCOMMANDTIME_MS = 300;
        s.CFG.MINIMUMSPEED_MPS = 0.05;
        s.CFG.DELTASTARTDELAY_MS = 100;
        s.CFG.DELTABRAKERELEASETIME_MS = 100;
        s.CFG.DELTABRAKEAPPLYTIME_MS = 100;
        s.CFG.DELTASTOPDISTANCE_MM = 100;
        s.CFG.DELTASTOPTIME_MS = 200;
        s.FB.RESET = true;
        s.FB.M1COMMANDACTIVE = false;
        s.FB.M2COMMANDACTIVE = false;
        s.FB.M1DIRECTION = 0;
        s.FB.M2DIRECTION = 0;
        s.FB.M1BRAKECMD = false;
        s.FB.M2BRAKECMD = false;
        s.FB.M1BRAKEAPPLIED = true;
        s.FB.M2BRAKEAPPLIED = true;
        s.FB.M1POSITION_M = 0.0;
        s.FB.M2POSITION_M = 0.0;
        s.FB.M1SPEED_MPS = 0.0;
        s.FB.M2SPEED_MPS = 0.0;
        s.FB.SYNCDEVIATION_M = 0.0;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = true;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = true;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = false;
        s.FB.M1POSITION_M = 0.0;
        s.FB.M2POSITION_M = 0.0;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 1.0;
        s.FB.SYNCDEVIATION_M = 0.4;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(600000000);
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = true;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = true;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = false;
        s.FB.M1POSITION_M = 0.6;
        s.FB.M2POSITION_M = 0.6;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 1.0;
        s.FB.SYNCDEVIATION_M = 0.4;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(600000000);
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = true;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 1;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = true;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = false;
        s.FB.M1POSITION_M = 1.2;
        s.FB.M2POSITION_M = 1.2;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 1.0;
        s.FB.SYNCDEVIATION_M = 0.4;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        s.FB.RESET = true;
        s.FB.M1COMMANDACTIVE = false;
        s.FB.M2COMMANDACTIVE = false;
        s.FB.M1DIRECTION = 0;
        s.FB.M2DIRECTION = 0;
        s.FB.M1BRAKECMD = false;
        s.FB.M2BRAKECMD = false;
        s.FB.M1BRAKEAPPLIED = true;
        s.FB.M2BRAKEAPPLIED = true;
        s.FB.M1POSITION_M = 0.0;
        s.FB.M2POSITION_M = 0.0;
        s.FB.M1SPEED_MPS = 0.0;
        s.FB.M2SPEED_MPS = 0.0;
        s.FB.SYNCDEVIATION_M = 0.0;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        if (!ctx.assert_eq(s.DAT.DELTASTARTDELAY_MS, 0, "DAT.DELTASTARTDELAY_MS", "0", 88, "Reset -> DeltaStartDelay_Ms remis a 0")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.DAT.MAXSYNCDEVIATION_M > 0.0), "DAT.MAXSYNCDEVIATION_M > 0.0", 89, "Reset -> MaxSyncDeviation_M remis a 0")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-T181-18c Non qualifie si un seul treuil commande'
bool test_3(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.CFG.MINIMUMCOMMANDTIME_MS = 300;
        s.CFG.MINIMUMSPEED_MPS = 0.05;
        s.CFG.DELTASTARTDELAY_MS = 100;
        s.CFG.DELTABRAKERELEASETIME_MS = 100;
        s.CFG.DELTABRAKEAPPLYTIME_MS = 100;
        s.CFG.DELTASTOPDISTANCE_MM = 100;
        s.CFG.DELTASTOPTIME_MS = 200;
        s.FB.RESET = true;
        s.FB.M1COMMANDACTIVE = false;
        s.FB.M2COMMANDACTIVE = false;
        s.FB.M1DIRECTION = 0;
        s.FB.M2DIRECTION = 0;
        s.FB.M1BRAKECMD = false;
        s.FB.M2BRAKECMD = false;
        s.FB.M1BRAKEAPPLIED = true;
        s.FB.M2BRAKEAPPLIED = true;
        s.FB.M1POSITION_M = 0.0;
        s.FB.M2POSITION_M = 0.0;
        s.FB.M1SPEED_MPS = 0.0;
        s.FB.M2SPEED_MPS = 0.0;
        s.FB.SYNCDEVIATION_M = 0.0;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = false;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 0;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = false;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = true;
        s.FB.M1POSITION_M = 0.0;
        s.FB.M2POSITION_M = 0.0;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 0.0;
        s.FB.SYNCDEVIATION_M = 0.3;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(1500000000);
        s.FB.RESET = false;
        s.FB.M1COMMANDACTIVE = true;
        s.FB.M2COMMANDACTIVE = false;
        s.FB.M1DIRECTION = 1;
        s.FB.M2DIRECTION = 0;
        s.FB.M1BRAKECMD = true;
        s.FB.M2BRAKECMD = false;
        s.FB.M1BRAKEAPPLIED = false;
        s.FB.M2BRAKEAPPLIED = true;
        s.FB.M1POSITION_M = 1.5;
        s.FB.M2POSITION_M = 0.0;
        s.FB.M1SPEED_MPS = 1.0;
        s.FB.M2SPEED_MPS = 0.0;
        s.FB.SYNCDEVIATION_M = 0.3;
        s.FB.CONFIG = s.CFG;
        s.FB.DATA = s.DAT;
        s.FB();
        s.FB.ENO = true;
        s.DAT = s.FB.DATA;
        if (!ctx.assert_false(static_cast<bool>(s.FB.SYMMETRYVALID), "FB.SYMMETRYVALID", 111, "Un seul treuil commande -> jamais qualifie")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

int main(int argc, char* argv[]) {
    bool json_mode = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--json") == 0) { json_mode = true; break; }
    }

    strucpp::TestRunner runner("test_fb_winch_symmetry.st");
    runner.set_json_mode(json_mode);
    runner.add("TC-P10-T181-18a Cycle symetrique -> SymmetryValid et SymmetryOk", test_1);
    runner.add("TC-P10-T181-18b Reset remet les mesures a zero", test_2);
    runner.add("TC-P10-T181-18c Non qualifie si un seul treuil commande", test_3);
    return runner.run();
}
