#include "generated.hpp"
#include "iec_test.hpp"
#include <cstring>

using namespace strucpp;

struct TestSetup_1 {
    FB_WINCH FB_W;
    ST_SPEEDSTEPTABLE TABLE;
    ST_FBWINCH_DRIVEREQUEST DRIVEREQ;
    ST_FBWINCH_SENSORS SENS;
    ST_FBWINCH_CFG CFG;

    void setup() {
    }

    void teardown() {
    }
};

// TEST 'TC-P03-001 Dynamique Enable : neutralisation initiale, transition Ready au repos, puis coupure'
bool test_1(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.CFG.SPEEDSTEPTABLE = s.TABLE;
        s.SENS.HOMED = true;
        s.SENS.CONTACTORSALLOFF = true;
        s.SENS.SPEEDGUARDREADY = true;
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = false;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 45, "Enable=FALSE -> Ready=FALSE (neutralise)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 58, "Enable=TRUE etabli -> Ready=TRUE (nominal)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = false;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 65, "Enable=FALSE -> Ready retombe a FALSE")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-011 Inversion Fwd<->Rev : neutre->sens immediat, inversion exige delai + rampe a 0'
bool test_2(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.CFG.SPEEDSTEPTABLE = s.TABLE;
        s.SENS.HOMED = true;
        s.SENS.CONTACTORSALLOFF = true;
        s.SENS.SPEEDGUARDREADY = true;
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 92, "Treuil pret")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 20.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 1, "FB_W.COMMANDEDDIRECTION", "1", 101, "Neutre->montee : CommandedDirection=1 immediat")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 102, "Neutre->montee : pas de pending")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 103, "Montee -> RelayFwd")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 114, "Arret -> StepNumber=0")) return false;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 0, "FB_W.COMMANDEDDIRECTION", "0", 115, "Arret via neutre : CommandedDirection=0 (relais/diagnostic neutres)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = -1;
        s.DRIVEREQ.SPEEDTGT_PCT = 20.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 124, "Inversion apres neutre -> DirectionChangePending=TRUE")) return false;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 125, "Inversion : rampe forcee a 0 pendant attente")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(400000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, -1, "FB_W.COMMANDEDDIRECTION", "-1", 131, "Apres 400ms -> CommandedDirection=-1")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 132, "Apres delai -> pending leve")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-011b Inversion via neutre : montee reelle -> relache neutre -> reprise descente -> temps mort + zero relais'
bool test_3(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.CFG.SPEEDSTEPTABLE = s.TABLE;
        s.SENS.HOMED = true;
        s.SENS.CONTACTORSALLOFF = true;
        s.SENS.SPEEDGUARDREADY = true;
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 159, "Treuil pret")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 90.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 1, "FB_W.COMMANDEDDIRECTION", "1", 168, "Montee reelle : CommandedDirection=1")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 169, "Montee reelle -> RelayFwd")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 179, "Neutre -> StepNumber=0")) return false;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 0, "FB_W.COMMANDEDDIRECTION", "0", 180, "Neutre -> CommandedDirection=0 (relais/diagnostic neutres)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 181, "Neutre -> RelayFwd coupe immediatement")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYREV), "FB_W.RELAYREV", 182, "Neutre -> RelayRev reste FALSE")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = -1;
        s.DRIVEREQ.SPEEDTGT_PCT = 20.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 191, "Reprise opposee apres neutre -> pending")) return false;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 192, "Reprise opposee -> StepNumber=0 (rampe a 0)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYREV), "FB_W.RELAYREV", 193, "Reprise opposee -> RelayRev retenu jusqu au delai")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(400000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, -1, "FB_W.COMMANDEDDIRECTION", "-1", 199, "Apres delai -> CommandedDirection=-1")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 200, "Apres delai -> pending leve")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYREV), "FB_W.RELAYREV", 201, "Apres delai -> RelayRev commande")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-011c Reprise du MEME sens apres neutre : depart immediat (pas de pending)'
bool test_4(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.CFG.SPEEDSTEPTABLE = s.TABLE;
        s.SENS.HOMED = true;
        s.SENS.CONTACTORSALLOFF = true;
        s.SENS.SPEEDGUARDREADY = true;
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 228, "Treuil pret")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 20.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 1, "FB_W.COMMANDEDDIRECTION", "1", 237, "Montee reelle : CommandedDirection=1")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 238, "Montee reelle -> RelayFwd")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 0, "FB_W.COMMANDEDDIRECTION", "0", 247, "Neutre -> CommandedDirection=0")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 20.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 1, "FB_W.COMMANDEDDIRECTION", "1", 256, "Reprise meme sens -> CommandedDirection=1 immediat")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 257, "Reprise meme sens -> pas de pending")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 258, "Reprise meme sens -> RelayFwd immediat")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-017 Config palier invalide : palier 0, sorties sures'
bool test_5(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 0.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 0.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 0.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 0.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 0.0;
        s.CFG.SPEEDSTEPTABLE = s.TABLE;
        s.SENS.HOMED = true;
        s.SENS.CONTACTORSALLOFF = true;
        s.SENS.SPEEDGUARDREADY = true;
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 50.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.FAULT.ERROR), "FB_W.FAULT.ERROR", 282, "Config invalide -> Error")) return false;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 283, "Config invalide -> palier 0")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 284, "Config invalide -> RelayFwd=FALSE (sortie sure)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYREV), "FB_W.RELAYREV", 285, "Config invalide -> RelayRev=FALSE")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.CONTACTOR1), "FB_W.CONTACTOR1", 286, "Config invalide -> Contactor1=FALSE")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-019 Ordre MainTask : Safety -> WinchControl -> PRG_06_Outputs'
bool test_6(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.CFG.SPEEDSTEPTABLE = s.TABLE;
        s.SENS.HOMED = true;
        s.SENS.CONTACTORSALLOFF = true;
        s.SENS.SPEEDGUARDREADY = true;
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 20.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 322, "Demande montee produite (consommee par PRG_06)")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.CONTACTOR1), "FB_W.CONTACTOR1", 323, "Palier 1 demande")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-042.1 Plafonds dynamiques palier : descente max 3, montee max 5, approche capteur haut=1'
bool test_7(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.CFG.SPEEDSTEPTABLE = s.TABLE;
        s.SENS.HOMED = true;
        s.SENS.CONTACTORSALLOFF = true;
        s.SENS.SPEEDGUARDREADY = true;
        s.DRIVEREQ.HOMINGAPPROACHACTIVE = false;
        s.SENS.CABLEPOSM = 0.0;
        s.CFG.SLOWDOWNDISTANCE_M = 1.0;
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = -1;
        s.DRIVEREQ.SPEEDTGT_PCT = 90.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 3, "FB_W.REQUESTEDSTEP", "3", 361, "Descente : palier cape a 3 (CfgMaxStepDescente)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = true;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 90.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 5, "FB_W.REQUESTEDSTEP", "5", 376, "Montee : palier 5 (MaxStepAscent)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = true;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 90.0;
        s.DRIVEREQ.HOMINGAPPROACHACTIVE = true;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 1, "FB_W.REQUESTEDSTEP", "1", 392, "Approche capteur haut : palier 1")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.DRIVEREQ.HOMINGAPPROACHACTIVE = false;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = true;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 90.0;
        s.DRIVEREQ.TOPLIMITM = 8.5;
        s.SENS.CABLEPOSM = 8.0;
        s.CFG.SLOWDOWNDISTANCE_M = 1.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.INTOPSLOWDOWNZONE), "FB_W.INTOPSLOWDOWNZONE", 411, "Zone ralentissement haut active")) return false;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 1, "FB_W.REQUESTEDSTEP", "1", 412, "Zone ralentissement haut : palier 1")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-052.1 Garde-fou vitesse : vitesse non-stable -> palier 1 (activation par defaut)'
bool test_8(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.CFG.SPEEDSTEPTABLE = s.TABLE;
        s.SENS.HOMED = true;
        s.SENS.CONTACTORSALLOFF = true;
        s.SENS.SPEEDGUARDREADY = true;
        s.DRIVEREQ.HOMINGAPPROACHACTIVE = false;
        s.SENS.CABLEPOSM = 0.0;
        s.CFG.SLOWDOWNDISTANCE_M = 1.0;
        s.DRIVEREQ.STARTSTOP = false;
        s.DRIVEREQ.DIRECTION = 0;
        s.DRIVEREQ.SPEEDTGT_PCT = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.DRIVEREQ.STARTSTOP = true;
        s.DRIVEREQ.DIRECTION = 1;
        s.DRIVEREQ.SPEEDTGT_PCT = 90.0;
        s.SENS.SPEEDGUARDREADY = false;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.DRIVEREQUEST = s.DRIVEREQ;
        s.FB_W.SENSORS = s.SENS;
        s.FB_W.CONFIG = s.CFG;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 1, "FB_W.REQUESTEDSTEP", "1", 453, "Vitesse non stable -> palier 1 (garde-fou)")) return false;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 1, "FB_W.STEPNUMBER", "1", 454, "Vitesse non stable -> StepNumber=1")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

int main(int argc, char* argv[]) {
    bool json_mode = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--json") == 0) { json_mode = true; break; }
    }

    strucpp::TestRunner runner("test_fb_winch.st");
    runner.set_json_mode(json_mode);
    runner.add("TC-P03-001 Dynamique Enable : neutralisation initiale, transition Ready au repos, puis coupure", test_1);
    runner.add("TC-P10-011 Inversion Fwd<->Rev : neutre->sens immediat, inversion exige delai + rampe a 0", test_2);
    runner.add("TC-P10-011b Inversion via neutre : montee reelle -> relache neutre -> reprise descente -> temps mort + zero relais", test_3);
    runner.add("TC-P10-011c Reprise du MEME sens apres neutre : depart immediat (pas de pending)", test_4);
    runner.add("TC-P10-017 Config palier invalide : palier 0, sorties sures", test_5);
    runner.add("TC-P10-019 Ordre MainTask : Safety -> WinchControl -> PRG_06_Outputs", test_6);
    runner.add("TC-P10-042.1 Plafonds dynamiques palier : descente max 3, montee max 5, approche capteur haut=1", test_7);
    runner.add("TC-P10-052.1 Garde-fou vitesse : vitesse non-stable -> palier 1 (activation par defaut)", test_8);
    return runner.run();
}
