#include "generated.hpp"
#include "iec_test.hpp"
#include <cstring>

using namespace strucpp;

struct TestSetup_1 {
    FB_SAFETY_EMERGENCYMANAGEMENT FB;

    void setup() {
    }

    void teardown() {
    }
};

// TEST 'TC-P03-001 Dynamique Enable : neutralisation initiale, transition Ready au repos, puis coupure'
bool test_1(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = false;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.READY), "FB.STATUS.READY", 11, "Enable=FALSE -> Ready=FALSE (neutralise)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 12, "Enable=FALSE -> Pas d erreur")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.READY), "FB.STATUS.READY", 19, "Enable=TRUE -> Ready=TRUE (nominal)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 20, "Au repos -> Pas d erreur")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = false;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.READY), "FB.STATUS.READY", 27, "Coupure -> Ready retombe a FALSE")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-SCEN-NOM Scenario Nominal : Sequence complete de rearmement sans blocage'
bool test_2(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 41, "Au repos boucle saine -> Armable=TRUE")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DONE), "FB.STATUS.DONE", 42, "Puissance non encore engagee -> Done=FALSE")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 1, "FB.STATUS.STATE.STEP", "1", 48, "Front ArmRequest lance TestA")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 49, "TestA coupe canal A")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 2, "FB.STATUS.STATE.STEP", "2", 55, "Boucle tombee -> RestoreA")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 56, "Canal A restaure")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 3, "FB.STATUS.STATE.STEP", "3", 62, "Boucle refermee -> TestB")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 63, "TestB coupe canal B")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 4, "FB.STATUS.STATE.STEP", "4", 69, "Boucle tombee -> RestoreB")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 70, "Canal B restaure")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 5, "FB.STATUS.STATE.STEP", "5", 76, "Auto-test A/B valide -> Step 5 Impulsion contacteur")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.ARMPULSE_CMD), "FB.CMD.ARMPULSE_CMD", 77, "Impulsion 1s active")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(1000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 6, "FB.STATUS.STATE.STEP", "6", 83, "Impulsion terminee -> Step 6 Confirmation")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.ARMPULSE_CMD), "FB.CMD.ARMPULSE_CMD", 84, "Impulsion retombe")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = true;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 90, "Contacteur confirme -> Retour repos IDLE")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DONE), "FB.STATUS.DONE", 91, "Puissance engagee -> Done=TRUE")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 92, "Cycle nominal termine sans defaut")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-SCEN-DYN Scenario Dynamique : Enchainement nominal puis perturbations reelles en service'
bool test_3(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(1000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = true;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DONE), "FB.STATUS.DONE", 120, "Machine armee en service")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(500000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = true;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 126, "Coupure metier -> Retombee immediate canal A")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 127, "Coupure metier -> Retombee immediate canal B")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 128, "Coupure metier active -> Armable=FALSE")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = true;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 134, "Rearmement refuse : reste a Step 0")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 140, "Defaut acquitte et disparu -> Armable redevient TRUE")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(1000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(2000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 166, "Echec collage contacteur -> Alarme levee")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 167, "Verrouillage Lockout 5s active")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 168, "Pendant lockout -> Armable=FALSE")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(5000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 174, "Lockout 5s expire")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 175, "Machine prete a etre reessayee")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-002 (partie AUTO) chaque canal est commande independamment, l autre reste maintenu'
bool test_4(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 194, "hors defaut, canal A maintenu")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 195, "hors defaut, canal B maintenu")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 1, "FB.STATUS.STATE.STEP", "1", 201, "front doit lancer TestA")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 202, "TestA : canal A seul doit se couper")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 203, "TestA : canal B ne doit PAS etre affecte")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 2, "FB.STATUS.STATE.STEP", "2", 209, "TestA reussi (boucle a reagi) -> RestoreA")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 210, "pas de defaut si le canal reagit correctement au test")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 211, "canal A restaure immediatement apres son test")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 3, "FB.STATUS.STATE.STEP", "3", 217, "RestoreA reussi -> TestB")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 218, "TestB : canal B seul doit se couper")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 219, "TestB : canal A ne doit PAS etre affecte")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 4, "FB.STATUS.STATE.STEP", "4", 225, "TestB reussi -> RestoreB")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 226, "pas de defaut si le canal B reagit correctement au test")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 227, "canal B restaure immediatement apres son test")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-003 front ArmRequest + boucle OK sur les 2 canaux -> pulse 1s puis confirmation'
bool test_5(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 5, "FB.STATUS.STATE.STEP", "5", 262, "les 2 canaux valides -> impulsion de reamement")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.ARMPULSE_CMD), "FB.CMD.ARMPULSE_CMD", 263, "pulse de reamement doit etre actif (TC-P01-003)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(1000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 6, "FB.STATUS.STATE.STEP", "6", 269, "pulse de 1s termine -> attente confirmation contacteur")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.ARMPULSE_CMD), "FB.CMD.ARMPULSE_CMD", 270, "pulse retombe apres 1s")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.BUSY), "FB.STATUS.BUSY", 271, "sequence toujours en cours (attente confirmation)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = true;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 277, "confirmation contacteur -> retour IDLE")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DONE), "FB.STATUS.DONE", 278, "contacteur engage confirme -> Done")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.BUSY), "FB.STATUS.BUSY", 279, "sequence terminee")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 280, "succes -> pas de lockout")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 281, "reamement reussi -> pas de defaut")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-004/009 Reset acquitte l affichage mais re-alarme si la cause persiste'
bool test_6(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 297, "precondition : canal colle doit avoir leve une erreur")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 303, "Reset doit effacer l affichage du defaut")) return false;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 304, "Reset seul ne relance jamais de sequence (pas de redemarrage auto)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 310, "TC-P01-004 : Reset seul ne doit PAS restaurer le maintien (interlock reste sur Cause, AF 3.4bis)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 1, "FB.STATUS.STATE.STEP", "1", 316, "un nouveau front ArmRequest doit relancer TestA")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 321, "cause persistante doit re-alarmer au nouvel essai, meme apres Reset")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-006 canal colle bloque le reamement (echec auto-test)'
bool test_7(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 1, "FB.STATUS.STATE.STEP", "1", 336, "front ArmRequest doit lancer TestA (step 1)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 342, "canal colle doit lever une erreur (RedundancyTestFailed)")) return false;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 343, "echec auto-test doit ramener la sequence a IDLE")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 344, "un canal colle bloque aussi le maintien normal (interlock sur Cause brute)")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-007 timeout confirmation contacteur -> lockout 5s'
bool test_8(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 5, "FB.STATUS.STATE.STEP", "5", 369, "les 2 canaux valides -> pulse")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(1000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 6, "FB.STATUS.STATE.STEP", "6", 375, "attente confirmation contacteur")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(2000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 381, "timeout confirmation doit ramener la sequence a IDLE")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 382, "timeout doit declencher le lockout (TC-P01-007)")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.ARMFAILED), "FB.STATUS.DIAG.ARMFAILED", 383, "timeout doit lever le defaut EmergencyArmingFailed")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 384, "defaut doit etre visible sur Error")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 390, "lockout actif doit bloquer toute nouvelle tentative de reamement")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(5000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 396, "lockout 5s ecoule -> leve automatiquement")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 1, "FB.STATUS.STATE.STEP", "1", 405, "apres le lockout, un nouveau front doit reellement relancer TestA (pas juste le drapeau qui retombe)")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-010 BtnEmergencyCutOff pendant le pulse de reamement (step 5) doit couper le pulse comme le maintien'
bool test_9(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 5, "FB.STATUS.STATE.STEP", "5", 430, "les 2 canaux valides -> pulse (step 5)")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.ARMPULSE_CMD), "FB.CMD.ARMPULSE_CMD", 431, "precondition : pulse actif")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = true;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 437, "BtnEmergencyCutOff coupe bien le maintien canal A (comportement attendu, deja correct)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 438, "BtnEmergencyCutOff coupe bien le maintien canal B (comportement attendu, deja correct)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.ARMPULSE_CMD), "FB.CMD.ARMPULSE_CMD", 444, "BtnEmergencyCutOff doit aussi couper le pulse de reamement en cours (coherence avec la coupure du maintien)")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-008 PowerCutOffRequest coupe A et B sans armer'
bool test_10(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 456, "hors defaut, canal A doit etre maintenu")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 457, "hors defaut, canal B doit etre maintenu")) return false;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 458, "pas de sequence en cours")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = true;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 464, "PowerCutOffRequest doit couper le canal A")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 465, "PowerCutOffRequest doit couper le canal B")) return false;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 466, "PowerCutOffRequest ne doit jamais declencher une sequence armement")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-001 Coupure AU physique (essai site, non automatise)'
bool test_11(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 478, "chaine AU ouverte -> Armable=FALSE (reflet logiciel de la coupure physique)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINA_CMD), "FB.CMD.MAINTAINA_CMD", 479, "chaine AU ouverte -> maintien canal A retombe")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.CMD.MAINTAINB_CMD), "FB.CMD.MAINTAINB_CMD", 480, "chaine AU ouverte -> maintien canal B retombe")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-005 Sequence 2 temps : ArmRequest sans Reset bloque ; Reset puis ArmRequest arme'
bool test_12(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(1000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(2000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 518, "precondition : lockout 5s actif apres echec")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 519, "precondition : Armable=FALSE sous lockout")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 525, "Temps 1 : ArmRequest sans Reset bloque -> reste Step 0")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 531, "Reset purge le lockout")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 532, "Reset acquitte l affichage du defaut")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 1, "FB.STATUS.STATE.STEP", "1", 538, "Temps 2 : Reset puis ArmRequest -> sequence armee (Step 1)")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-011 PowerCutOffRequest pendant l impulsion (step 5) -> abandon 16#0010 + lockout + Error=FALSE'
bool test_13(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 5, "FB.STATUS.STATE.STEP", "5", 570, "les 2 canaux valides -> pulse (step 5)")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.CMD.ARMPULSE_CMD), "FB.CMD.ARMPULSE_CMD", 571, "precondition : pulse actif")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = true;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 577, "PowerCutOff pendant pulse -> sequence ramenee a IDLE")) return false;
        if (!ctx.assert_eq(s.FB.STATUS.DIAG.LASTABORTCAUSE, 0x0010, "FB.STATUS.DIAG.LASTABORTCAUSE", "16#0010", 578, "cause abandon = 16#0010 (PowerCutOff metier)")) return false;
        if (!ctx.assert_eq(s.FB.STATUS.DIAG.LASTABORTSTEP, 5, "FB.STATUS.DIAG.LASTABORTSTEP", "5", 579, "abandon a l etape 5 (impulsion)")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 580, "lockout 5s actif apres coupure metier")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 581, "coupure metier voulue -> PAS de defaut d armement (Error=FALSE)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 582, "interlock : PowerCutOffRequest actif -> Armable=FALSE")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-012 Armable=1 mais rearmement echoue a l etape 5 (PowerCutOff pendant pulse)'
bool test_14(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 592, "precondition : Armable=TRUE (rearmement autorise)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 1, "FB.STATUS.STATE.STEP", "1", 598, "ArmRequest -> sequence lancee (step 1)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 5, "FB.STATUS.STATE.STEP", "5", 613, "les 2 canaux valides -> pulse (step 5)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = true;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 619, "echec a l etape 5 -> sequence ramenee a IDLE")) return false;
        if (!ctx.assert_eq(s.FB.STATUS.DIAG.LASTABORTSTEP, 5, "FB.STATUS.DIAG.LASTABORTSTEP", "5", 620, "abandon a l etape 5")) return false;
        if (!ctx.assert_eq(s.FB.STATUS.DIAG.LASTABORTCAUSE, 0x0010, "FB.STATUS.DIAG.LASTABORTCAUSE", "16#0010", 621, "cause = 16#0010 (PowerCutOff metier)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DONE), "FB.STATUS.DONE", 622, "rearmement NON abouti (Done=FALSE, contacteur non engage)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 623, "echec silencieux : PAS de defaut d armement (Error=FALSE)")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P01-013 Recuperation Reset : cause latched -> Reset -> cause levee -> rearmement reussi'
bool test_15(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 5, "FB.STATUS.STATE.STEP", "5", 648, "pulse (step 5)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = true;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.DIAG.LASTABORTCAUSE, 0x0010, "FB.STATUS.DIAG.LASTABORTCAUSE", "16#0010", 654, "cause latched = 16#0010")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 655, "lockout actif")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = true;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.LOCKOUTACTIVE), "FB.STATUS.DIAG.LOCKOUTACTIVE", 661, "Reset purge le lockout")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.STATE.ARMABLE), "FB.STATUS.STATE.ARMABLE", 662, "cause levee + Reset -> Armable=TRUE")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = true;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 1, "FB.STATUS.STATE.STEP", "1", 668, "nouveau front ArmRequest -> sequence relancee")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = false;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(200000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(1000000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = false;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 6, "FB.STATUS.STATE.STEP", "6", 684, "pulse termine -> attente confirmation")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB.ENABLE = true;
        s.FB.RESET = false;
        s.FB.ARMREQUEST = false;
        s.FB.POWERCUTOFFREQUEST = false;
        s.FB.BTNEMERGENCYCUTOFF = false;
        s.FB.EMERGENCYCHAINCLOSED = true;
        s.FB.POWERCONTACTORENGAGED = true;
        s.FB();
        s.FB.ENO = true;
        if (!ctx.assert_eq(s.FB.STATUS.STATE.STEP, 0, "FB.STATUS.STATE.STEP", "0", 688, "contacteur confirme -> retour IDLE")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB.STATUS.DONE), "FB.STATUS.DONE", 689, "rearmement reussi (Done=TRUE)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB.STATUS.DIAG.ERROR), "FB.STATUS.DIAG.ERROR", 690, "aucun defaut apres reussite")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

int main(int argc, char* argv[]) {
    bool json_mode = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--json") == 0) { json_mode = true; break; }
    }

    strucpp::TestRunner runner("test_fb_safety_emergency.st");
    runner.set_json_mode(json_mode);
    runner.add("TC-P03-001 Dynamique Enable : neutralisation initiale, transition Ready au repos, puis coupure", test_1);
    runner.add("TC-P01-SCEN-NOM Scenario Nominal : Sequence complete de rearmement sans blocage", test_2);
    runner.add("TC-P01-SCEN-DYN Scenario Dynamique : Enchainement nominal puis perturbations reelles en service", test_3);
    runner.add("TC-P01-002 (partie AUTO) chaque canal est commande independamment, l autre reste maintenu", test_4);
    runner.add("TC-P01-003 front ArmRequest + boucle OK sur les 2 canaux -> pulse 1s puis confirmation", test_5);
    runner.add("TC-P01-004/009 Reset acquitte l affichage mais re-alarme si la cause persiste", test_6);
    runner.add("TC-P01-006 canal colle bloque le reamement (echec auto-test)", test_7);
    runner.add("TC-P01-007 timeout confirmation contacteur -> lockout 5s", test_8);
    runner.add("TC-P01-010 BtnEmergencyCutOff pendant le pulse de reamement (step 5) doit couper le pulse comme le maintien", test_9);
    runner.add("TC-P01-008 PowerCutOffRequest coupe A et B sans armer", test_10);
    runner.add("TC-P01-001 Coupure AU physique (essai site, non automatise)", test_11);
    runner.add("TC-P01-005 Sequence 2 temps : ArmRequest sans Reset bloque ; Reset puis ArmRequest arme", test_12);
    runner.add("TC-P01-011 PowerCutOffRequest pendant l impulsion (step 5) -> abandon 16#0010 + lockout + Error=FALSE", test_13);
    runner.add("TC-P01-012 Armable=1 mais rearmement echoue a l etape 5 (PowerCutOff pendant pulse)", test_14);
    runner.add("TC-P01-013 Recuperation Reset : cause latched -> Reset -> cause levee -> rearmement reussi", test_15);
    return runner.run();
}
