// Generated by STruC++ - IEC 61131-3 Structured Text to C++ Compiler
// Do not edit this file manually.

#include "FB_Cycle.hpp"

namespace strucpp {

// Library: iec-standard-fb
R_TRIG::R_TRIG() {
    // Initialize variables
}

void R_TRIG::operator()() {
    Q = (CLK) & (!M);
    M = CLK;
}

TON::TON() {
    // Initialize variables
}

void TON::operator()() {
    CURRENT_TIME = TIME();
    if (((((STATE == 0)) & (NOT(PREV_IN))) & (IN))) {
        STATE = 1;
        Q = false;
        START_TIME = CURRENT_TIME;
    } else {
        if ((NOT(IN))) {
            ET = 0LL;
            Q = false;
            STATE = 0;
        } else if ((STATE == 1)) {
            if (((START_TIME + PT) <= CURRENT_TIME)) {
                STATE = 2;
                Q = true;
                ET = PT;
            } else {
                ET = CURRENT_TIME - START_TIME;
            }
        }
    }
    PREV_IN = IN;
}


}  // namespace strucpp
// Generated by STruC++ - IEC 61131-3 Structured Text to C++ Compiler
// Do not edit this file manually.

#include "FB_Cycle.hpp"

namespace strucpp {

FB_FAULTCORE::FB_FAULTCORE() {
    // Initialize variables
}

void FB_FAULTCORE::operator()() {
    READY = ENABLE;
    RESETEDGE.CLK = RESET;
    RESETEDGE();
    RESETEDGE.ENO = true;
    if (RESETEDGE.Q) {
        for (I = 0; I <= 15; I++) {
            LATCH.at(I) = false;
        }
    }
    FAULT.ERRORID = 0;
    if (ENABLE) {
        for (I = 0; I <= 15; I++) {
            if (CAUSES.at(I).ACTIVE) {
                FAULT.ERRORID = (FAULT.ERRORID) | (SHL(static_cast<IEC_WORD>(1), TO_DWORD(I)));
            }
        }
    }
    FAULT.ERROR = (FAULT.ERRORID != 0);
    if (ENABLE) {
        for (I = 0; I <= 15; I++) {
            if ((CAUSES.at(I).ACTIVE) & (CAUSES.at(I).LATCHING)) {
                LATCH.at(I) = true;
            }
        }
    }
    FAULT.LATCHEDID = 0;
    for (I = 0; I <= 15; I++) {
        if (LATCH.at(I)) {
            FAULT.LATCHEDID = (FAULT.LATCHEDID) | (SHL(static_cast<IEC_WORD>(1), TO_DWORD(I)));
        }
    }
    FAULT.LATCHED = (FAULT.LATCHEDID != 0);
}

}  // namespace strucpp
// Generated by STruC++ - IEC 61131-3 Structured Text to C++ Compiler
// Do not edit this file manually.

#include "FB_Cycle.hpp"

namespace strucpp {

FB_CYCLE::FB_CYCLE()
    : STATE(E_CYCLESTEP::X0_PREPARATION), SAVEDSTATE(E_CYCLESTEP::X0_PREPARATION), PAUSEDSTATE(E_CYCLESTEP::X0_PREPARATION), WAITINGRESUME(false), SAMPLECOUNTDONE(false), CTRLASCENTDISTM(2.0), CTRLASCENTTOLERANCEM(0.25), CTRLASCENTTIMEOUT(30000000000LL), DRAININGTIME(5000000000LL), STEPMAXTIMEOUT(60000000000LL)
{
    // Initialize variables
}

void FB_CYCLE::operator()() {
    RESETEDGE.CLK = RESET;
    RESETEDGE();
    RESETEDGE.ENO = true;
    STARTEDGE.CLK = STARTCYCLE;
    STARTEDGE();
    STARTEDGE.ENO = true;
    DEADMANARMEDEDGE.CLK = DEADMANARMED;
    DEADMANARMEDEDGE();
    DEADMANARMEDEDGE.ENO = true;
    ABORTEDGE.CLK = ABORTCYCLE;
    ABORTEDGE();
    ABORTEDGE.ENO = true;
    ENABLEEDGE.CLK = ENABLE;
    ENABLEEDGE();
    ENABLEEDGE.ENO = true;
    STABILIZATIONTIMER.IN = (STATE == E_CYCLESTEP::X7_CTRL_ASCENT);
    STABILIZATIONTIMER.PT = CTRLASCENTTIMEOUT;
    STABILIZATIONTIMER();
    STABILIZATIONTIMER.ENO = true;
    SPEEDMISMATCHMPS = ABS(M1_MEASUREDSPEEDMPS - M2_MEASUREDSPEEDMPS);
    SPEEDMISMATCHACTIVE = (((((STATE == E_CYCLESTEP::X7_CTRL_ASCENT)) & (CYCLEMOTIONPERMIT)) & ((SPEEDMISMATCHTHRESHOLDMPS > 0.0))) & ((SPEEDMISMATCHTIMEOUT > 0LL))) & ((SPEEDMISMATCHMPS > SPEEDMISMATCHTHRESHOLDMPS));
    SPEEDMISMATCHTIMER.IN = SPEEDMISMATCHACTIVE;
    SPEEDMISMATCHTIMER.PT = SPEEDMISMATCHTIMEOUT;
    SPEEDMISMATCHTIMER();
    SPEEDMISMATCHTIMER.ENO = true;
    SPEEDMISMATCHCONFIRMED = SPEEDMISMATCHTIMER.Q;
    STEPMAXTIMER.IN = (((CYCLEMOTIONPERMIT) & ((STATE != E_CYCLESTEP::X0_PREPARATION))) & ((STATE != E_CYCLESTEP::X13_DONE_SYNC))) & ((STATE != E_CYCLESTEP::STABILIZING));
    STEPMAXTIMER.PT = STEPMAXTIMEOUT;
    STEPMAXTIMER();
    STEPMAXTIMER.ENO = true;
    INSTCAUSES.at(0).ACTIVE = (LIMITLEGALREACHED) & ((STATE == E_CYCLESTEP::X4_DESCEND_OPEN));
    INSTCAUSES.at(0).LATCHING = true;
    INSTCAUSES.at(0).TEXTE = "Limite legale de profondeur atteinte pendant descente";
    INSTCAUSES.at(1).ACTIVE = ((WINCHSYNCERROR) & ((STATE != E_CYCLESTEP::X0_PREPARATION))) & ((STATE != E_CYCLESTEP::STABILIZING));
    INSTCAUSES.at(1).LATCHING = true;
    INSTCAUSES.at(1).TEXTE = "Desynchronisme treuils M1/M2 bloquant";
    INSTCAUSES.at(2).ACTIVE = ((SPEEDMISMATCHCONFIRMED) & ((STATE != E_CYCLESTEP::X0_PREPARATION))) & ((STATE != E_CYCLESTEP::STABILIZING));
    INSTCAUSES.at(2).LATCHING = true;
    INSTCAUSES.at(2).TEXTE = "Ecart de vitesse M1/M2 confirme en montee";
    INSTCAUSES.at(3).ACTIVE = ((!HEARTBEATIHMOK) & ((STATE != E_CYCLESTEP::X0_PREPARATION))) & ((STATE != E_CYCLESTEP::STABILIZING));
    INSTCAUSES.at(3).LATCHING = true;
    INSTCAUSES.at(3).TEXTE = "Perte communication IHM pendant cycle";
    INSTCAUSES.at(4).ACTIVE = (STEPMAXTIMER.Q) & ((STATE != E_CYCLESTEP::STABILIZING));
    INSTCAUSES.at(4).LATCHING = true;
    INSTCAUSES.at(4).TEXTE = "Depassement tempo maximale d etape (blocage mouvement)";
    INSTCAUSES.at(5).ACTIVE = (((STABILIZATIONTIMER.Q) | ((ABS(M1_CABLEPOSM - M2_CABLEPOSM) > CTRLASCENTTOLERANCEM)))) & ((STATE == E_CYCLESTEP::X7_CTRL_ASCENT));
    INSTCAUSES.at(5).LATCHING = true;
    INSTCAUSES.at(5).TEXTE = "Defaut de stabilisation / tolerance ecart codeurs en remontee controle";
    INSTFAULT.ENABLE = ENABLE;
    INSTFAULT.RESET = RESET;
    INSTFAULT.CAUSES = INSTCAUSES;
    INSTFAULT();
    INSTFAULT.ENO = true;
    FAULT = INSTFAULT.FAULT;
    ERROREDGE.CLK = FAULT.ERROR;
    ERROREDGE();
    ERROREDGE.ENO = true;
    if ((!ENABLE) | (!POWERCONTACTORENGAGED)) {
        WINCHM1CMD.STARTSTOP = false;
        WINCHM1CMD.DIRECTION = 0;
        WINCHM1CMD.SPEEDPCT = 0.0;
        WINCHM2CMD.STARTSTOP = false;
        WINCHM2CMD.DIRECTION = 0;
        WINCHM2CMD.SPEEDPCT = 0.0;
        TRANSLATIONCMD.START = false;
        TRANSLATIONCMD.TARGET = 0;
        BUCKETCMD.OPEN = false;
        BUCKETCMD.CLOSE = false;
        BUCKETCMD.KOBOLDCONTACTORCMD = false;
        if ((((STATE != E_CYCLESTEP::X0_PREPARATION)) & ((STATE != E_CYCLESTEP::X13_DONE_SYNC))) & ((STATE != E_CYCLESTEP::STABILIZING))) {
            PAUSEDSTATE = STATE;
            WAITINGRESUME = true;
        }
        CYCLESTEP = STATE;
        CYCLESTATESTR = "Cycle desactive : securite absente ou mode hors semi-auto";
        READY = false;
        LIFECYCLE.BUSY = false;
        LIFECYCLE.DONE = false;
        SPEEDMISMATCHTIMER.IN = false;
        SPEEDMISMATCHTIMER.PT = SPEEDMISMATCHTIMEOUT;
        SPEEDMISMATCHTIMER();
        SPEEDMISMATCHTIMER.ENO = true;
        SPEEDMISMATCHMPS = 0.0;
        SPEEDMISMATCHACTIVE = false;
        SPEEDMISMATCHCONFIRMED = false;
        OPERATORACTIONID = 0;
        OPERATORACTION = "Passer en mode Semi-Auto et engager la securite pour activer le cycle.";
        EXPECTEDAXIS = E_OPERATORAXIS::NONE;
        EXPECTEDDIRECTION = 0;
        WAITINGFOROPERATOR = false;
        WAITINGFORPROCESS = false;
        REQUESTACTIVE = false;
        return;
    }
    READY = (ENABLE) & (!FAULT.LATCHED);
    if (ERROREDGE.Q) {
        CYCLESTEPATERROR = STATE;
        STATE = E_CYCLESTEP::STABILIZING;
    }
    if (RESETEDGE.Q) {
        SAVEDSTATE = E_CYCLESTEP::X0_PREPARATION;
        if (STATE == E_CYCLESTEP::STABILIZING) {
            STATE = E_CYCLESTEP::X0_PREPARATION;
        }
    }
    if (ABORTEDGE.Q) {
        STATE = E_CYCLESTEP::X0_PREPARATION;
        WAITINGRESUME = false;
        PAUSEDSTATE = E_CYCLESTEP::X0_PREPARATION;
    }
    if (WAITINGRESUME) {
        WINCHM1CMD.STARTSTOP = false;
        WINCHM1CMD.DIRECTION = 0;
        WINCHM1CMD.SPEEDPCT = 0.0;
        WINCHM2CMD.STARTSTOP = false;
        WINCHM2CMD.DIRECTION = 0;
        WINCHM2CMD.SPEEDPCT = 0.0;
        TRANSLATIONCMD.START = false;
        TRANSLATIONCMD.TARGET = 0;
        BUCKETCMD.OPEN = false;
        BUCKETCMD.CLOSE = false;
        BUCKETCMD.KOBOLDCONTACTORCMD = false;
        CYCLESTEP = PAUSEDSTATE;
        CYCLESTATESTR = "Cycle en pause : reprise consciente requise (StartCycle).";
        WAITINGFOROPERATOR = true;
        WAITINGFORPROCESS = false;
        OPERATORACTIONID = 0x0400;
        OPERATORACTION = "Reprendre le cycle : appuyer sur StartCycle.";
        EXPECTEDAXIS = E_OPERATORAXIS::BUTTON;
        EXPECTEDDIRECTION = 0;
        REQUESTACTIVE = false;
        if (STARTEDGE.Q) {
            WAITINGRESUME = false;
        }
        return;
    }
    switch (STATE) {
        case E_CYCLESTEP::X0_PREPARATION:
            CYCLESTEP = E_CYCLESTEP::X0_PREPARATION;
            CYCLESTATESTR = "X0 - Verification coherence systeme";
            WINCHM1CMD.STARTSTOP = false;
            WINCHM1CMD.DIRECTION = 0;
            WINCHM1CMD.SPEEDPCT = 0.0;
            WINCHM2CMD.STARTSTOP = false;
            WINCHM2CMD.DIRECTION = 0;
            WINCHM2CMD.SPEEDPCT = 0.0;
            TRANSLATIONCMD.START = false;
            TRANSLATIONCMD.TARGET = 0;
            BUCKETCMD.OPEN = false;
            BUCKETCMD.CLOSE = false;
            BUCKETCMD.KOBOLDCONTACTORCMD = false;
            LIFECYCLE.BUSY = false;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::BUTTON;
            EXPECTEDDIRECTION = 0;
            WAITINGFOROPERATOR = true;
            WAITINGFORPROCESS = false;
            OPERATORACTIONID = 0x0400;
            OPERATORACTION = "Demander le demarrage du cycle (Bouton IHM ou armement Homme-Mort).";
            if ((((STARTEDGE.Q) | (DEADMANARMEDEDGE.Q))) & (!FAULT.ERROR)) {
                WAITINGRESUME = false;
                SAMPLECOUNTDONE = false;
                STATE = E_CYCLESTEP::X1_HOMING;
            }
            break;
        case E_CYCLESTEP::X1_HOMING:
            CYCLESTEP = E_CYCLESTEP::X1_HOMING;
            CYCLESTATESTR = "X1 - Referencement codeurs (vitesses lentes)";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_Y;
            EXPECTEDDIRECTION = 1;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x0401;
            OPERATORACTION = "Maintenir la montee lente vers les capteurs de referencement.";
            if ((!HOMEDM1) | (!HOMEDM2)) {
                WINCHM1CMD.STARTSTOP = CYCLEMOTIONPERMIT;
                WINCHM1CMD.DIRECTION = 1;
                WINCHM1CMD.SPEEDPCT = 10.0;
                WINCHM2CMD.STARTSTOP = CYCLEMOTIONPERMIT;
                WINCHM2CMD.DIRECTION = 1;
                WINCHM2CMD.SPEEDPCT = 10.0;
                if (HOMINGREQUEST) {
                    STATE = E_CYCLESTEP::X2_WORK_POS_SELECT;
                }
            } else {
                STATE = E_CYCLESTEP::X2_WORK_POS_SELECT;
            }
            break;
        case E_CYCLESTEP::X2_WORK_POS_SELECT:
            CYCLESTEP = E_CYCLESTEP::X2_WORK_POS_SELECT;
            CYCLESTATESTR = "X2 - Selection position travail";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_X;
            EXPECTEDDIRECTION = 0;
            WAITINGFOROPERATOR = ((SELTARGET == 0)) | (!CYCLEMOTIONPERMIT);
            WAITINGFORPROCESS = ((SELTARGET != 0)) & (CYCLEMOTIONPERMIT);
            OPERATORACTIONID = 0x0402;
            OPERATORACTION = "Selectionner la cible et maintenir la translation vers la position de travail.";
            if ((((SELTARGET == 1)) | ((SELTARGET == 3))) | ((SELTARGET == 4))) {
                SELECTEDWORKTARGET = SELTARGET;
                TRANSLATIONCMD.TARGET = SELTARGET;
                TRANSLATIONCMD.START = CYCLEMOTIONPERMIT;
                if ((CYCLEMOTIONPERMIT) & ((((((SELTARGET == 1) & (TRANSLATION_AT_TREMIE))) | (((SELTARGET == 3) & (TRANSLATION_AT_P1)))) | (((SELTARGET == 4) & (TRANSLATION_AT_MAINTENANCE)))))) {
                    TRANSLATIONCMD.START = false;
                    STATE = E_CYCLESTEP::X3_OPEN_BUCKET;
                }
            }
            break;
        case E_CYCLESTEP::X3_OPEN_BUCKET:
            CYCLESTEP = E_CYCLESTEP::X3_OPEN_BUCKET;
            CYCLESTATESTR = "X3 - Ouverture benne";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_Y;
            EXPECTEDDIRECTION = 0;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x0403;
            OPERATORACTION = "Maintenir le joystick : ouverture complete de la benne.";
            if (BENNE_ISOPEN) {
                STATE = E_CYCLESTEP::X4_DESCEND_OPEN;
            } else {
                BUCKETCMD.OPEN = CYCLEMOTIONPERMIT;
                if (((CYCLEMOTIONPERMIT) & (BENNE_DONE)) & (BENNE_ISOPEN)) {
                    BUCKETCMD.OPEN = false;
                    STATE = E_CYCLESTEP::X4_DESCEND_OPEN;
                }
            }
            break;
        case E_CYCLESTEP::X4_DESCEND_OPEN:
            CYCLESTEP = E_CYCLESTEP::X4_DESCEND_OPEN;
            CYCLESTATESTR = "X4 - Plongee benne ouverte (synchro)";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_Y;
            EXPECTEDDIRECTION = -1;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x0404;
            OPERATORACTION = "Maintenir la descente : plongee synchro et detection fond Kobold.";
            WINCHM1CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM1CMD.DIRECTION = -1;
            WINCHM1CMD.SPEEDPCT = 50.0;
            WINCHM2CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM2CMD.DIRECTION = -1;
            WINCHM2CMD.SPEEDPCT = 50.0;
            BUCKETCMD.KOBOLDCONTACTORCMD = true;
            if ((CYCLEMOTIONPERMIT) & (KOBOLDCONTACTFOND)) {
                WINCHM1CMD.STARTSTOP = false;
                WINCHM2CMD.STARTSTOP = false;
                BUCKETCMD.KOBOLDCONTACTORCMD = false;
                TOUCHPOSITIONM = M1_CABLEPOSM;
                if (LIMITLEGALDEPTHM < -0.01) {
                    RAISETARGETM = MAX(TOUCHPOSITIONM + 0.5, LIMITLEGALDEPTHM + 0.5);
                } else {
                    RAISETARGETM = TOUCHPOSITIONM + 0.5;
                }
                STATE = E_CYCLESTEP::X5_BOTTOM_CONFIRMED;
            }
            break;
        case E_CYCLESTEP::X5_BOTTOM_CONFIRMED:
            CYCLESTEP = E_CYCLESTEP::X5_BOTTOM_CONFIRMED;
            CYCLESTATESTR = "X5 - Fond confirme : remontee securisee";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_Y;
            EXPECTEDDIRECTION = 1;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x0405;
            OPERATORACTION = "Fond confirme : maintenir la montee jusqu a la hauteur de fermeture.";
            WINCHM1CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM1CMD.DIRECTION = 1;
            WINCHM1CMD.SPEEDPCT = 20.0;
            WINCHM2CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM2CMD.DIRECTION = 1;
            WINCHM2CMD.SPEEDPCT = 20.0;
            if (((CYCLEMOTIONPERMIT) & ((M1_CABLEPOSM >= RAISETARGETM))) & ((M2_CABLEPOSM >= RAISETARGETM))) {
                WINCHM1CMD.STARTSTOP = false;
                WINCHM2CMD.STARTSTOP = false;
                STATE = E_CYCLESTEP::X6_CLOSE_BUCKET;
            }
            break;
        case E_CYCLESTEP::X6_CLOSE_BUCKET:
            CYCLESTEP = E_CYCLESTEP::X6_CLOSE_BUCKET;
            CYCLESTATESTR = "X6 - Fermeture benne (tolerance a peu pres ferme)";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_Y;
            EXPECTEDDIRECTION = 1;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x0406;
            OPERATORACTION = "Maintenir la commande : fermeture de la benne.";
            WINCHM1CMD.STARTSTOP = false;
            BUCKETCMD.CLOSE = true;
            if ((CYCLEMOTIONPERMIT) & (((BENNE_DONE) & (((BENNE_ISCLOSED) | (BENNE_ISROUGHLYCLOSED)))))) {
                BUCKETCMD.CLOSE = false;
                STATE = E_CYCLESTEP::X7_CTRL_ASCENT;
            }
            break;
        case E_CYCLESTEP::X7_CTRL_ASCENT:
            CYCLESTEP = E_CYCLESTEP::X7_CTRL_ASCENT;
            CYCLESTATESTR = "X7 - Remontee lente de controle";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_Y;
            EXPECTEDDIRECTION = 1;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x0407;
            OPERATORACTION = "Maintenir la montee lente : palier de controle et synchronisme.";
            WINCHM1CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM1CMD.DIRECTION = 1;
            WINCHM1CMD.SPEEDPCT = 20.0;
            WINCHM2CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM2CMD.DIRECTION = 1;
            WINCHM2CMD.SPEEDPCT = 20.0;
            if ((((CYCLEMOTIONPERMIT) & ((M1_CABLEPOSM >= (TOUCHPOSITIONM + CTRLASCENTDISTM)))) & ((M2_CABLEPOSM >= (TOUCHPOSITIONM + CTRLASCENTDISTM)))) & ((ABS(M1_CABLEPOSM - M2_CABLEPOSM) <= CTRLASCENTTOLERANCEM))) {
                STATE = E_CYCLESTEP::X8_ASCENT_LOADED;
            }
            break;
        case E_CYCLESTEP::X8_ASCENT_LOADED:
            CYCLESTEP = E_CYCLESTEP::X8_ASCENT_LOADED;
            CYCLESTATESTR = "X8 - Remontee en charge";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_Y;
            EXPECTEDDIRECTION = 1;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x0408;
            OPERATORACTION = "Maintenir la montee en charge jusqu a la limite haute.";
            WINCHM1CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM1CMD.DIRECTION = 1;
            WINCHM1CMD.SPEEDPCT = 70.0;
            WINCHM2CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM2CMD.DIRECTION = 1;
            WINCHM2CMD.SPEEDPCT = 70.0;
            if ((CYCLEMOTIONPERMIT) & (M1_CABLEPOSM >= CABLELIMITM1ASCENTM)) {
                WINCHM1CMD.STARTSTOP = false;
                WINCHM2CMD.STARTSTOP = false;
                STATE = E_CYCLESTEP::X9_DRAIN_PAUSE;
            }
            break;
        case E_CYCLESTEP::X9_DRAIN_PAUSE:
            CYCLESTEP = E_CYCLESTEP::X9_DRAIN_PAUSE;
            CYCLESTATESTR = "X9 - Egouttage du godet en cours";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::NONE;
            EXPECTEDDIRECTION = 0;
            WAITINGFOROPERATOR = false;
            WAITINGFORPROCESS = true;
            OPERATORACTIONID = 0x0409;
            OPERATORACTION = "Egouttage du godet en cours (temporisation).";
            WINCHM1CMD.STARTSTOP = false;
            WINCHM2CMD.STARTSTOP = false;
            DRAININGTIMER.IN = true;
            DRAININGTIMER.PT = DRAININGTIME;
            DRAININGTIMER();
            DRAININGTIMER.ENO = true;
            if ((CYCLEMOTIONPERMIT) & (DRAININGTIMER.Q)) {
                DRAININGTIMER.IN = false;
                DRAININGTIMER();
                DRAININGTIMER.ENO = true;
                STATE = E_CYCLESTEP::X10_TRANSLATE_DUMP;
            }
            break;
        case E_CYCLESTEP::X10_TRANSLATE_DUMP:
            CYCLESTEP = E_CYCLESTEP::X10_TRANSLATE_DUMP;
            CYCLESTATESTR = "X10 - Deplacement vers tremie (grille/crible libres)";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_X;
            EXPECTEDDIRECTION = -1;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x040A;
            OPERATORACTION = "Maintenir la translation vers la tremie de dechargement.";
            TRANSLATIONCMD.TARGET = 1;
            TRANSLATIONCMD.START = CYCLEMOTIONPERMIT;
            if ((CYCLEMOTIONPERMIT) & (TRANSLATION_AT_TREMIE)) {
                TRANSLATIONCMD.START = false;
                STATE = E_CYCLESTEP::X11_OPEN_DUMP;
            }
            break;
        case E_CYCLESTEP::X11_OPEN_DUMP:
            CYCLESTEP = E_CYCLESTEP::X11_OPEN_DUMP;
            CYCLESTATESTR = "X11 - Vidange / ouverture du godet (montee possible, descente ouvre)";
            LIFECYCLE.BUSY = true;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::JOYSTICK_Y;
            EXPECTEDDIRECTION = -1;
            WAITINGFOROPERATOR = !CYCLEMOTIONPERMIT;
            WAITINGFORPROCESS = CYCLEMOTIONPERMIT;
            OPERATORACTIONID = 0x040B;
            OPERATORACTION = "Deflechir vers le bas pour ouvrir la benne et vider la charge.";
            WINCHM1CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM1CMD.DIRECTION = 1;
            WINCHM1CMD.SPEEDPCT = 20.0;
            WINCHM2CMD.STARTSTOP = CYCLEMOTIONPERMIT;
            WINCHM2CMD.DIRECTION = 1;
            WINCHM2CMD.SPEEDPCT = 20.0;
            BUCKETCMD.OPEN = CYCLEMOTIONPERMIT;
            if (((CYCLEMOTIONPERMIT) & (BENNE_DONE)) & (BENNE_ISOPEN)) {
                BUCKETCMD.OPEN = false;
                STATE = E_CYCLESTEP::X13_DONE_SYNC;
            }
            break;
        case E_CYCLESTEP::X13_DONE_SYNC:
            CYCLESTEP = E_CYCLESTEP::X13_DONE_SYNC;
            CYCLESTATESTR = "X13 - Cycle automatique complete - pret";
            WINCHM1CMD.STARTSTOP = false;
            WINCHM2CMD.STARTSTOP = false;
            TRANSLATIONCMD.START = false;
            LIFECYCLE.DONE = true;
            LIFECYCLE.BUSY = false;
            EXPECTEDAXIS = E_OPERATORAXIS::BUTTON;
            EXPECTEDDIRECTION = 0;
            WAITINGFOROPERATOR = true;
            WAITINGFORPROCESS = false;
            OPERATORACTIONID = 0x040D;
            OPERATORACTION = "Cycle termine avec succes. Relancer un nouveau cycle.";
            if (!SAMPLECOUNTDONE) {
                SAMPLECOUNT = SAMPLECOUNT + 1;
                SAMPLECOUNTDONE = true;
            }
            if (STARTEDGE.Q) {
                SAMPLECOUNTDONE = false;
                LIFECYCLE.DONE = false;
                STATE = E_CYCLESTEP::X0_PREPARATION;
            }
            break;
        case E_CYCLESTEP::STABILIZING:
            CYCLESTEP = E_CYCLESTEP::STABILIZING;
            CYCLESTATESTR = "X14 - Cycle en attente / stabilisation (STAB)";
            WINCHM1CMD.STARTSTOP = false;
            WINCHM2CMD.STARTSTOP = false;
            TRANSLATIONCMD.START = false;
            BUCKETCMD.OPEN = false;
            BUCKETCMD.CLOSE = false;
            LIFECYCLE.BUSY = false;
            LIFECYCLE.DONE = false;
            EXPECTEDAXIS = E_OPERATORAXIS::BUTTON;
            EXPECTEDDIRECTION = 0;
            WAITINGFOROPERATOR = true;
            WAITINGFORPROCESS = false;
            OPERATORACTIONID = 0x0480;
            OPERATORACTION = "Cycle stabilise sur anomalie : acquitter le defaut pour reinitialiser.";
            break;
    }
    if ((LIFECYCLE.BUSY) & (!CYCLEMOTIONPERMIT)) {
        WINCHM1CMD.STARTSTOP = false;
        WINCHM2CMD.STARTSTOP = false;
        TRANSLATIONCMD.START = false;
        BUCKETCMD.OPEN = false;
        BUCKETCMD.CLOSE = false;
        BUCKETCMD.KOBOLDCONTACTORCMD = false;
    }
    REQUESTACTIVE = ((((WINCHM1CMD.STARTSTOP) | (WINCHM2CMD.STARTSTOP)) | (TRANSLATIONCMD.START)) | (BUCKETCMD.OPEN)) | (BUCKETCMD.CLOSE);
}

}  // namespace strucpp