#include "generated.hpp"
#include "iec_test.hpp"
#include <cstring>

using namespace strucpp;

struct TestSetup_1 {
    FB_WINCH FB_W;
    ST_SPEEDSTEPTABLE TABLE;

    void setup() {
    }

    void teardown() {
    }
};

// TEST 'TC-P03-001 Dynamique Enable : neutralisation initiale, transition Ready au repos, puis coupure'
bool test_1(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.FB_W.ENABLE = false;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 35, "Enable=FALSE -> Ready=FALSE (neutralise)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 52, "Enable=TRUE etabli -> Ready=TRUE (nominal)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = false;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 61, "Enable=FALSE -> Ready retombe a FALSE")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-011 Inversion Fwd<->Rev : neutre->sens immediat, inversion exige delai + rampe a 0'
bool test_2(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 85, "Treuil pret")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 20.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 1, "FB_W.COMMANDEDDIRECTION", "1", 93, "Neutre->montee : CommandedDirection=1 immediat")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 94, "Neutre->montee : pas de pending")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 95, "Montee -> RelayFwd")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 105, "Arret -> StepNumber=0")) return false;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 0, "FB_W.COMMANDEDDIRECTION", "0", 106, "Arret via neutre : CommandedDirection=0 (relais/diagnostic neutres)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = -1;
        s.FB_W.SPEEDTGT_PCT = 20.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 114, "Inversion apres neutre -> DirectionChangePending=TRUE")) return false;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 115, "Inversion : rampe forcee a 0 pendant attente")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(400000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = -1;
        s.FB_W.SPEEDTGT_PCT = 20.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, -1, "FB_W.COMMANDEDDIRECTION", "-1", 123, "Apres 400ms -> CommandedDirection=-1")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 124, "Apres delai -> pending leve")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-011b Inversion via neutre : montee reelle -> relache neutre -> reprise descente -> temps mort + zero relais'
bool test_3(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 148, "Treuil pret")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 90.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 1, "FB_W.COMMANDEDDIRECTION", "1", 156, "Montee reelle : CommandedDirection=1")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 157, "Montee reelle -> RelayFwd")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 166, "Neutre -> StepNumber=0")) return false;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 0, "FB_W.COMMANDEDDIRECTION", "0", 167, "Neutre -> CommandedDirection=0 (relais/diagnostic neutres)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 168, "Neutre -> RelayFwd coupe immediatement")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYREV), "FB_W.RELAYREV", 169, "Neutre -> RelayRev reste FALSE")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = -1;
        s.FB_W.SPEEDTGT_PCT = 20.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 177, "Reprise opposee apres neutre -> pending")) return false;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 178, "Reprise opposee -> StepNumber=0 (rampe a 0)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYREV), "FB_W.RELAYREV", 179, "Reprise opposee -> RelayRev retenu jusqu au delai")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(400000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = -1;
        s.FB_W.SPEEDTGT_PCT = 20.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, -1, "FB_W.COMMANDEDDIRECTION", "-1", 187, "Apres delai -> CommandedDirection=-1")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 188, "Apres delai -> pending leve")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYREV), "FB_W.RELAYREV", 189, "Apres delai -> RelayRev commande")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-011c Reprise du MEME sens apres neutre : depart immediat (pas de pending)'
bool test_4(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.READY), "FB_W.READY", 213, "Treuil pret")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 20.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 1, "FB_W.COMMANDEDDIRECTION", "1", 221, "Montee reelle : CommandedDirection=1")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 222, "Montee reelle -> RelayFwd")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 0, "FB_W.COMMANDEDDIRECTION", "0", 230, "Neutre -> CommandedDirection=0")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 20.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.COMMANDEDDIRECTION, 1, "FB_W.COMMANDEDDIRECTION", "1", 238, "Reprise meme sens -> CommandedDirection=1 immediat")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.DIRECTIONCHANGEPENDING), "FB_W.DIRECTIONCHANGEPENDING", 239, "Reprise meme sens -> pas de pending")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 240, "Reprise meme sens -> RelayFwd immediat")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-017 Config palier invalide : palier 0, sorties sures'
bool test_5(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 0.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 0.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 0.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 0.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 0.0;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 50.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 50.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.FAULT.ERROR), "FB_W.FAULT.ERROR", 261, "Config invalide -> Error")) return false;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 0, "FB_W.STEPNUMBER", "0", 262, "Config invalide -> palier 0")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 263, "Config invalide -> RelayFwd=FALSE (sortie sure)")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.RELAYREV), "FB_W.RELAYREV", 264, "Config invalide -> RelayRev=FALSE")) return false;
        if (!ctx.assert_false(static_cast<bool>(s.FB_W.CONTACTOR1), "FB_W.CONTACTOR1", 265, "Config invalide -> Contactor1=FALSE")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-019 Ordre MainTask : Safety -> WinchControl -> PRG_06_Outputs'
bool test_6(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 20.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.RELAYFWD), "FB_W.RELAYFWD", 295, "Demande montee produite (consommee par PRG_06)")) return false;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.CONTACTOR1), "FB_W.CONTACTOR1", 296, "Palier 1 demande")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-042.1 Plafonds dynamiques palier : descente max 3, montee max 5, approche capteur haut=1'
bool test_7(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = -1;
        s.FB_W.SPEEDTGT_PCT = 90.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 3, "FB_W.REQUESTEDSTEP", "3", 327, "Descente : palier cape a 3 (CfgMaxStepDescente)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = true;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 90.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 5, "FB_W.REQUESTEDSTEP", "5", 340, "Montee : palier 5 (MaxStepAscent)")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = true;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 90.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.HOMINGAPPROACHACTIVE = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 1, "FB_W.REQUESTEDSTEP", "1", 353, "Approche capteur haut : palier 1")) return false;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = true;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 90.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.CABLEPOSM = 8.0;
        s.FB_W.TOPLIMITM = 8.5;
        s.FB_W.CFGSLOWDOWNDISTANCEM = 1.0;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_true(static_cast<bool>(s.FB_W.INTOPSLOWDOWNZONE), "FB_W.INTOPSLOWDOWNZONE", 367, "Zone ralentissement haut active")) return false;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 1, "FB_W.REQUESTEDSTEP", "1", 368, "Zone ralentissement haut : palier 1")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

// TEST 'TC-P10-052.1 Garde-fou vitesse : vitesse non-stable -> palier 1 (activation par defaut)'
bool test_8(strucpp::TestContext& ctx) {
    TestSetup_1 s;
    s.setup();
    bool __passed = [&]() -> bool {
        s.TABLE.STEPTHRESHOLD_PCT.at(1) = 10.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(2) = 30.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(3) = 50.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(4) = 70.0;
        s.TABLE.STEPTHRESHOLD_PCT.at(5) = 90.0;
        s.TABLE.P2R1 = true;
        s.TABLE.P3R1 = true;
        s.TABLE.P4R1 = true;
        s.TABLE.P5R1 = true;
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = false;
        s.FB_W.DIRECTION = 0;
        s.FB_W.SPEEDTGT_PCT = 0.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = true;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        strucpp::__CURRENT_TIME_NS += static_cast<int64_t>(10000000);
        s.FB_W.ENABLE = true;
        s.FB_W.RESET = false;
        s.FB_W.STARTSTOP = true;
        s.FB_W.DIRECTION = 1;
        s.FB_W.SPEEDTGT_PCT = 90.0;
        s.FB_W.POWERCONTACTORENGAGED = true;
        s.FB_W.HOMED = true;
        s.FB_W.FWDREVSPEEDFEEDBACKOFF = true;
        s.FB_W.SPEEDGUARDREADY = false;
        s.FB_W.SPEEDSTEPTABLE = s.TABLE;
        s.FB_W();
        s.FB_W.ENO = true;
        if (!ctx.assert_eq(s.FB_W.REQUESTEDSTEP, 1, "FB_W.REQUESTEDSTEP", "1", 401, "Vitesse non stable -> palier 1 (garde-fou)")) return false;
        if (!ctx.assert_eq(s.FB_W.STEPNUMBER, 1, "FB_W.STEPNUMBER", "1", 402, "Vitesse non stable -> StepNumber=1")) return false;
        return true;
    }();
    s.teardown();
    return __passed;
}

int main(int argc, char* argv[]) {
    bool json_mode = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--json") == 0) { json_mode = true; break; }
    }

    strucpp::TestRunner runner("test_fb_winch.st");
    runner.set_json_mode(json_mode);
    runner.add("TC-P03-001 Dynamique Enable : neutralisation initiale, transition Ready au repos, puis coupure", test_1);
    runner.add("TC-P10-011 Inversion Fwd<->Rev : neutre->sens immediat, inversion exige delai + rampe a 0", test_2);
    runner.add("TC-P10-011b Inversion via neutre : montee reelle -> relache neutre -> reprise descente -> temps mort + zero relais", test_3);
    runner.add("TC-P10-011c Reprise du MEME sens apres neutre : depart immediat (pas de pending)", test_4);
    runner.add("TC-P10-017 Config palier invalide : palier 0, sorties sures", test_5);
    runner.add("TC-P10-019 Ordre MainTask : Safety -> WinchControl -> PRG_06_Outputs", test_6);
    runner.add("TC-P10-042.1 Plafonds dynamiques palier : descente max 3, montee max 5, approche capteur haut=1", test_7);
    runner.add("TC-P10-052.1 Garde-fou vitesse : vitesse non-stable -> palier 1 (activation par defaut)", test_8);
    return runner.run();
}
